services:
  # --- SERVIDOR PRINCIPAL (SOLO PARA LINUX) ---
  arduino-lab:
    build: .
    container_name: arduino-lab
    ports:
      - "5000:5000"
    devices:
      - "${PORT_ARDUINO}:${PORT_ARDUINO}"
    # Permisos para que Docker pueda usar el puerto serie
    group_add:
      - dialout
    environment:
      - PORT_ARDUINO=${PORT_ARDUINO}
      - FLASK_ENV=development
    volumes:
      - .:/app

  # --- TÚNEL PÚBLICO ---
  localtunnel:
    image: node:18-alpine
    container_name: arduino-tunnel
    command: npx localtunnel --port 5000 --subdomain lab-tdf --local-host arduino-lab
    depends_on:
      - arduino-lab